require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
  - 'bin/**'
  - 'db/schema.rb'
  - 'db/migrate/**'
  - 'config/initializers/simple_form_bootstrap.rb'
  - 'config/initializers/devise.rb'
  - 'config/initializers/simple_form.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false