require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
  - 'bin/**'
  - 'db/schema.rb'
  - 'db/migrate/**'
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'config/initializers/**'

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false