require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
  - 'bin/**'
  - 'db/schema.rb'
  - 'db/migrate/**'
  - 'vendor/**/*'
  - 'node_modules/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false